-- Import direct des produits via SQL
-- À exécuter dans l'interface PostgreSQL de Railway

-- 1. Créer les catégories si elles n'existent pas
INSERT INTO categories (name) VALUES 
('Farine'), ('Congel'), ('Sachet'), ('Divers'), ('Boite'), ('Frigo'), ('Patissier')
ON CONFLICT (name) DO NOTHING;

-- 2. Insérer tous les produits d'un coup
INSERT INTO products (name, stock, stock_minimal, category_id) VALUES 
-- Catégorie Farine
('Semoule baguettes', 50, 50, (SELECT id FROM categories WHERE name = 'Farine')),
('Oumeyma', 50, 50, (SELECT id FROM categories WHERE name = 'Farine')),
('Natural supra', 25, 25, (SELECT id FROM categories WHERE name = 'Farine')),
('Alpha', 20, 20, (SELECT id FROM categories WHERE name = 'Farine')),
('Levure Bruggeman', 6, 6, (SELECT id FROM categories WHERE name = 'Farine')),
('S500 puratos', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),
('Boscous', 10, 10, (SELECT id FROM categories WHERE name = 'Farine')),
('Seigle', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),
('Decor cereales', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),
('Sucre', 15, 15, (SELECT id FROM categories WHERE name = 'Farine')),
('Sucre P4', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),
('Sel', 10, 10, (SELECT id FROM categories WHERE name = 'Farine')),
('Sésames', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),
('Son', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),
('Semoule harcha', 3, 3, (SELECT id FROM categories WHERE name = 'Farine')),
('Œufs', 6, 6, (SELECT id FROM categories WHERE name = 'Farine')),
('Papier cuisson 40x60', 5, 5, (SELECT id FROM categories WHERE name = 'Farine')),
('Papier cuisson 80x60', 2, 2, (SELECT id FROM categories WHERE name = 'Farine')),

-- Catégorie Congel
('Croissant chocolat', 5, 5, (SELECT id FROM categories WHERE name = 'Congel')),
('Croquant noisette chocolat', 4, 4, (SELECT id FROM categories WHERE name = 'Congel')),
('Noix de pécan', 4, 4, (SELECT id FROM categories WHERE name = 'Congel')),
('Croissant amande', 5, 5, (SELECT id FROM categories WHERE name = 'Congel')),
('Amande cerise', 4, 4, (SELECT id FROM categories WHERE name = 'Congel')),
('Boule de Berlin', 3, 3, (SELECT id FROM categories WHERE name = 'Congel')),
('Croissant nature', 2, 2, (SELECT id FROM categories WHERE name = 'Congel')),
('Couque au chocolat', 2, 2, (SELECT id FROM categories WHERE name = 'Congel')),
('Maton', 2, 2, (SELECT id FROM categories WHERE name = 'Congel')),
('Mini pecan', 2, 2, (SELECT id FROM categories WHERE name = 'Congel')),

-- Catégorie Sachet
('P1', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('P2', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('P4', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('P6', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('Petit pain', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('Grand pain Carré', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('Grand pain Rond', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('1 baguette', 3, 3, (SELECT id FROM categories WHERE name = 'Sachet')),
('2 baguettes', 3, 3, (SELECT id FROM categories WHERE name = 'Sachet')),
('Sandwich', 5, 5, (SELECT id FROM categories WHERE name = 'Sachet')),
('Sac plastique', 10, 10, (SELECT id FROM categories WHERE name = 'Sachet')),

-- Catégorie Divers
('Bobines papier', 10, 10, (SELECT id FROM categories WHERE name = 'Divers')),
('Papier toilette', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Carton 1000cc', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Carton 2000cc', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Pots de wraps de 12 oz', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Touillettes à café.', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Serviettes sandwiches', 3, 3, (SELECT id FROM categories WHERE name = 'Divers')),
('Rouleaux bancontact', 3, 3, (SELECT id FROM categories WHERE name = 'Divers')),
('Gants noirs taille L', 5, 5, (SELECT id FROM categories WHERE name = 'Divers')),
('Petit gobelet à café', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Couvercle Petit gobelet à café', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Moyen gobelet à café', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Couvercle Moyen gobelet à café', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Grand gobelet à café', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Couvercle Grand gobelet à café', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Emballage Salade bowl 750', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Rouleau film pvc 45cm', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Aluminium 45cm', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Produit four', 3, 3, (SELECT id FROM categories WHERE name = 'Divers')),
('Bidon liquide vaisselle + rinçage', 2, 2, (SELECT id FROM categories WHERE name = 'Divers')),
('Savon mains', 3, 3, (SELECT id FROM categories WHERE name = 'Divers')),
('Javel', 10, 10, (SELECT id FROM categories WHERE name = 'Divers')),
('Dasty', 10, 10, (SELECT id FROM categories WHERE name = 'Divers')),

-- Catégorie Boite
('11/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('13/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('15/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('17/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('19/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('21/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('23/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('25/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('27/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('30/8', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('19/11', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('21/11', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('23/11', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('25/11', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('27/11', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('30/11', 5, 5, (SELECT id FROM categories WHERE name = 'Boite')),
('35/10', 2, 2, (SELECT id FROM categories WHERE name = 'Boite')),
('40/10', 2, 2, (SELECT id FROM categories WHERE name = 'Boite')),

-- Catégorie Frigo
('Pâte filo', 3, 3, (SELECT id FROM categories WHERE name = 'Frigo')),
('Saumon', 4, 4, (SELECT id FROM categories WHERE name = 'Frigo')),
('Fromage blanc', 4, 4, (SELECT id FROM categories WHERE name = 'Frigo')),
('Mascarpone', 10, 10, (SELECT id FROM categories WHERE name = 'Frigo')),

-- Catégorie Patissier
('CHOCOLAT BLANC', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CHOCOLAT AU LAIT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CHOCOLAT NOIR 811', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BATONS CHOCOLAT 300pc', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PEPITES CHOCOLAT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('GRAINS DE CAFE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CHOCOLAT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('POUDRE DE CACAO', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('FONDANT BLANC', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('FONDANT CHOCOLAT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('GLUCOSE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('DELI CARAMEL', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('POIRES CONSERVES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('ABRICOT CONSERVES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CERISES CONSERVES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CORIN D''ABRICOT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('DECORGEL NEUTRAL', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('MIROIR NEUTRE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PRALINE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('MIROIR CHOCOLAT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PATE A SUCRE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BEURRE DE CACAO', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SOUS GATEAUX 16CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SOUS GATEAUX 18 CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SOUS GATEAUX 20 CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SOUS GATEAUX 22 CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SOUS GATEAUX 24 CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('LANGUETTES CARR NOIR 8CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CAISSETTES RONDES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CAISSETTES OVALES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CAISSETTES TRIANGULAIRES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CAISSETTES CALYPSO', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CARTONS D''OR 60/40', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('ASSIETTES RONDES NOIRES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BAVARIX 5CM', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('COLORANTS', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('MACARONS CHOCOLAT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('FEUILLTINE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BRESILIENNE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('GELATINE POUDRE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BACKING', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('VANILLE LIQUIDE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('VANILLE POUDRE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CAFÉ TRABLE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SUCRE SO', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SUCRE RAFTISNOW', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('RAISAINS SECS', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('POUDRE D''AMANDE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('AMANDES ÉFILÉES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('AMANDES HACHÉES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('AMANDES CONCASSÉES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PAILLETTES CHOCO NOIR', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PAILLETTES CHOCO BLANC', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('MERINGUES 200PCS', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('SPECULOOS CONCASSÉES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BONBONNES DE GAZ', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('CREME PATISSIERE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BISCUIT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('VEGETOP SUCRE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('VEGETOP SANS SUCRE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BLANC D''ŒUF', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('JAUNE D''OEUF', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('BEURRE MONTAIGU', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('MARGARINE MIRA', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('FROMAGE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('RIZ DEBIC PRECUIT', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PURÉE DE FRAMBOISE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PURÉE DE PASSION', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PURÉE DE FRAISE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PURÉE DE MANGUE', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('PURÉE DE CITRON', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier')),
('FRAMBOISES CONGELÉES', 0, 0, (SELECT id FROM categories WHERE name = 'Patissier'))

ON CONFLICT (name) DO UPDATE SET
    stock = EXCLUDED.stock,
    stock_minimal = EXCLUDED.stock_minimal;

-- Vérification
SELECT 
    c.name as category,
    COUNT(p.id) as nb_products
FROM categories c
LEFT JOIN products p ON c.id = p.category_id
GROUP BY c.name
ORDER BY c.name;
